### ISSUE TITLE
Crash on a LUKS image

### ISSUE THREAD

**Issue by baruch** [baruch/gpart#9]
Fedora issue https://bugzilla.redhat.com/show_bug.cgi?id=1258174:

There is a crash when trying to run gpart on a luks image:

    gpart -v /dev/mapper/luks-854657c3-3ec5-4a09-9357-e004c4839038

```
[New LWP 8077]
Core was generated by `gpart -v /dev/mapper/luks-854657c3-3ec5-4a09-9357-e004c4839038'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00000000004032f1 in disk_geometry (d=d@entry=0x19f96a0) at disku.c:86
86	disku.c: No such file or directory.

Thread 1 (LWP 8077):
#0  0x00000000004032f1 in disk_geometry (d=d@entry=0x19f96a0) at disku.c:86
        g = {d_c = 0, d_h = 0, d_s = 0, d_nsecs = 490228575}
        nsects = 490228575
        hg = {heads = 0 '\000', sectors = 0 '\000', cylinders = 0, start = 0}
        st = {st_dev = 6, st_ino = 88180, st_nlink = 1, st_mode = 25008, st_uid = 0, st_gid = 6, __pad0 = 0, st_rdev = 64770, st_size = 0, st_blksize = 4096, st_blocks = 0, st_atim = {tv_sec = 1440884950, tv_nsec = 338282602}, st_mtim = {tv_sec = 1440884912, tv_nsec = 761585919}, st_ctim = {tv_sec = 1440884912, tv_nsec = 761585919}, __unused = {0, 0, 0}}
        lba = <optimized out>
#1  0x0000000000402803 in get_disk_desc (sectsize=0, dev=0x7fff0bb7b70e "/dev/mapper/luks-854657c3-3ec5-4a09-9357-e004c4839038") at gpart.c:829
        ubuf = 0x19f4690 ""
        buf = 0x19f5000 ""
        psize = 4096
        d = 0x19f96a0
        ssize = <optimized out>
        dg = <optimized out>
#2  main (ac=<optimized out>, av=<optimized out>) at gpart.c:1809
        optstr = 0x407340 "b:C:cdEefghiK:k:Ll:n:qs:t:VvW:w:"
        p1 = <optimized out>
        p2 = <optimized out>
        p3 = <optimized out>
        odev = 0x0
        backup = 0x0
        opt = <optimized out>
        sectsize = 0
        no_of_incons = 0
        d = 0x19f96a0
From                To                  Syms Read   Shared Object Library
0x00007f2b9ea98ed0  0x00007f2b9ea999d0  Yes         /lib64/libdl.so.2
0x00007f2b9e6f9560  0x00007f2b9e83ab24  Yes         /lib64/libc.so.6
0x00007f2b9ec9cb10  0x00007f2b9ecb5c30  Yes         /lib64/ld-linux-x86-64.so.2
$1 = 0x0
No symbol "__glib_assert_msg" in current context.
rax            0x1d384b5f	490228575
rbx            0x19f96a0	27236000
rcx            0x0	0
rdx            0x0	0
rsi            0x0	0
rdi            0x0	0
rbp            0x7fff0bb7b70e	0x7fff0bb7b70e
rsp            0x7fff0bb7b0e0	0x7fff0bb7b0e0
r8             0x1	1
r9             0x73	115
r10            0x7fff0bb7aea0	140733389975200
r11            0x246	582
r12            0x0	0
r13            0x7fff0bb7b410	140733389976592
r14            0x0	0
r15            0x19f96a0	27236000
rip            0x4032f1	0x4032f1 <disk_geometry+225>
eflags         0x10246	[ PF ZF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
st0            0	(raw 0x00000000000000000000)
st1            0	(raw 0x00000000000000000000)
st2            0	(raw 0x00000000000000000000)
st3            0	(raw 0x00000000000000000000)
st4            0	(raw 0x00000000000000000000)
st5            0	(raw 0x00000000000000000000)
st6            0	(raw 0x00000000000000000000)
st7            0	(raw 0x00000000000000000000)
fctrl          0x37f	895
fstat          0x0	0
ftag           0xffff	65535
fiseg          0x0	0
fioff          0x0	0
foseg          0x0	0
fooff          0x0	0
fop            0x0	0
mxcsr          0x1f80	[ IM DM ZM OM UM PM ]
ymm0           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 11 times>, 0xff, 0x0 <repeats 20 times>}, v16_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0xff00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x0, 0x0, 0xff000000, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0xff000000, 0x0, 0x0}, v2_int128 = {0x00000000ff0000000000000000000000, 0x00000000000000000000000000000000}}
ymm1           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x8000000000000000, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x76 <repeats 16 times>, 0x0 <repeats 16 times>}, v16_int16 = {0x7676, 0x7676, 0x7676, 0x7676, 0x7676, 0x7676, 0x7676, 0x7676, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x76767676, 0x76767676, 0x76767676, 0x76767676, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x7676767676767676, 0x7676767676767676, 0x0, 0x0}, v2_int128 = {0x76767676767676767676767676767676, 0x00000000000000000000000000000000}}
ymm2           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm3           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm4           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm5           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm6           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm7           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm8           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm9           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm10          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm11          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm12          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x8000000000000000, 0x0, 0x0}, v32_int8 = {0x0 <repeats 15 times>, 0xff, 0x0 <repeats 16 times>}, v16_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int32 = {0x0, 0x0, 0x0, 0xff000000, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0xff00000000000000, 0x0, 0x0}, v2_int128 = {0xff000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm13          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm14          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
ymm15          {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
Dump of assembler code for function disk_geometry:
   0x0000000000403210 <+0>:	push   %rbx
   0x0000000000403211 <+1>:	mov    %rdi,%rbx
   0x0000000000403214 <+4>:	sub    $0xc0,%rsp
   0x000000000040321b <+11>:	movq   $0x0,0x205f9a(%rip)        # 0x6091c0 <g.4372>
   0x0000000000403226 <+22>:	movq   $0x0,0x205f97(%rip)        # 0x6091c8 <g.4372+8>
   0x0000000000403231 <+33>:	movq   $0x0,0x205f94(%rip)        # 0x6091d0 <g.4372+16>
   0x000000000040323c <+44>:	movq   $0x0,0x205f91(%rip)        # 0x6091d8 <g.4372+24>
   0x0000000000403247 <+55>:	lea    0x20(%rsp),%rdx
   0x000000000040324c <+60>:	mov    (%rdi),%rsi
   0x000000000040324f <+63>:	mov    $0x1,%edi
   0x0000000000403254 <+68>:	mov    %fs:0x28,%rax
   0x000000000040325d <+77>:	mov    %rax,0xb8(%rsp)
   0x0000000000403265 <+85>:	xor    %eax,%eax
   0x0000000000403267 <+87>:	callq  0x400f80 <__xstat@plt>
   0x000000000040326c <+92>:	test   %eax,%eax
   0x000000000040326e <+94>:	jne    0x403284 <disk_geometry+116>
   0x0000000000403270 <+96>:	mov    0x38(%rsp),%eax
   0x0000000000403274 <+100>:	and    $0xf000,%eax
   0x0000000000403279 <+105>:	cmp    $0x8000,%eax
   0x000000000040327e <+110>:	je     0x403320 <disk_geometry+272>
   0x0000000000403284 <+116>:	mov    0x8(%rbx),%edi
   0x0000000000403287 <+119>:	lea    0x10(%rsp),%rdx
   0x000000000040328c <+124>:	xor    %eax,%eax
   0x000000000040328e <+126>:	mov    $0x301,%esi
   0x0000000000403293 <+131>:	callq  0x400ed0 <ioctl@plt>
   0x0000000000403298 <+136>:	cmp    $0xffffffff,%eax
   0x000000000040329b <+139>:	je     0x403400 <disk_geometry+496>
   0x00000000004032a1 <+145>:	mov    0x8(%rbx),%edi
   0x00000000004032a4 <+148>:	lea    0x8(%rsp),%rdx
   0x00000000004032a9 <+153>:	xor    %eax,%eax
   0x00000000004032ab <+155>:	mov    $0x1260,%esi
   0x00000000004032b0 <+160>:	callq  0x400ed0 <ioctl@plt>
   0x00000000004032b5 <+165>:	cmp    $0xffffffff,%eax
   0x00000000004032b8 <+168>:	je     0x403430 <disk_geometry+544>
   0x00000000004032be <+174>:	movzbl 0x10(%rsp),%esi
   0x00000000004032c3 <+179>:	movzbl 0x11(%rsp),%ecx
   0x00000000004032c8 <+184>:	mov    0x8(%rsp),%rax
   0x00000000004032cd <+189>:	movzbl %cl,%edi
   0x00000000004032d0 <+192>:	movzbl %sil,%edx
   0x00000000004032d4 <+196>:	mov    %rax,0x205efd(%rip)        # 0x6091d8 <g.4372+24>
   0x00000000004032db <+203>:	imul   %edi,%edx
   0x00000000004032de <+206>:	mov    %rsi,0x205ee3(%rip)        # 0x6091c8 <g.4372+8>
   0x00000000004032e5 <+213>:	mov    %rcx,0x205ee4(%rip)        # 0x6091d0 <g.4372+16>
   0x00000000004032ec <+220>:	movslq %edx,%rdi
   0x00000000004032ef <+223>:	xor    %edx,%edx
=> 0x00000000004032f1 <+225>:	div    %rdi
   0x00000000004032f4 <+228>:	mov    %rax,0x205ec5(%rip)        # 0x6091c0 <g.4372>
   0x00000000004032fb <+235>:	mov    0xb8(%rsp),%rbx
   0x0000000000403303 <+243>:	xor    %fs:0x28,%rbx
   0x000000000040330c <+252>:	mov    $0x6091c0,%eax
   0x0000000000403311 <+257>:	jne    0x40345a <disk_geometry+586>
   0x0000000000403317 <+263>:	add    $0xc0,%rsp
   0x000000000040331e <+270>:	pop    %rbx
   0x000000000040331f <+271>:	retq   
   0x0000000000403320 <+272>:	mov    0x50(%rsp),%rax
   0x0000000000403325 <+277>:	lea    0x1ff(%rax),%rdx
   0x000000000040332c <+284>:	test   %rax,%rax
   0x000000000040332f <+287>:	cmovs  %rdx,%rax
   0x0000000000403333 <+291>:	sar    $0x9,%rax
   0x0000000000403337 <+295>:	test   %rax,%rax
   0x000000000040333a <+298>:	mov    %rax,0x8(%rsp)
   0x000000000040333f <+303>:	mov    %rax,%rdi
   0x0000000000403342 <+306>:	jne    0x40335d <disk_geometry+333>
   0x0000000000403344 <+308>:	mov    $0x1,%dil
   0x0000000000403347 <+311>:	mov    $0x4061d0,%edx
   0x000000000040334c <+316>:	mov    $0x4061ee,%esi
   0x0000000000403351 <+321>:	xor    %eax,%eax
   0x0000000000403353 <+323>:	callq  0x405230 <pr>
   0x0000000000403358 <+328>:	mov    0x8(%rsp),%rdi
   0x000000000040335d <+333>:	lea    -0x1(%rdi),%rsi
   0x0000000000403361 <+337>:	movabs $0x410410410410411,%rdx
   0x000000000040336b <+347>:	mov    %rdi,0x205e66(%rip)        # 0x6091d8 <g.4372+24>
   0x0000000000403372 <+354>:	mov    %rsi,%rax
   0x0000000000403375 <+357>:	mul    %rdx
   0x0000000000403378 <+360>:	mov    %rsi,%rax
   0x000000000040337b <+363>:	sub    %rdx,%rax
   0x000000000040337e <+366>:	shr    %rax
   0x0000000000403381 <+369>:	lea    (%rdx,%rax,1),%rcx
   0x0000000000403385 <+373>:	movabs $0x8080808080808081,%rdx
   0x000000000040338f <+383>:	shr    $0x5,%rcx
   0x0000000000403393 <+387>:	mov    %rcx,%rax
   0x0000000000403396 <+390>:	mov    %rcx,%rbx
   0x0000000000403399 <+393>:	mul    %rdx
   0x000000000040339c <+396>:	shr    $0x7,%rdx
   0x00000000004033a0 <+400>:	mov    %rdx,%rax
   0x00000000004033a3 <+403>:	shl    $0x8,%rax
   0x00000000004033a7 <+407>:	sub    %rdx,%rax
   0x00000000004033aa <+410>:	movabs $0x515565a6aabafc1,%rdx
   0x00000000004033b4 <+420>:	sub    %rax,%rbx
   0x00000000004033b7 <+423>:	mov    %rcx,%rax
   0x00000000004033ba <+426>:	shl    $0x6,%rax
   0x00000000004033be <+430>:	mov    %rbx,0x205e03(%rip)        # 0x6091c8 <g.4372+8>
   0x00000000004033c5 <+437>:	mov    %rsi,%rbx
   0x00000000004033c8 <+440>:	sub    %rcx,%rax
   0x00000000004033cb <+443>:	sub    %rax,%rbx
   0x00000000004033ce <+446>:	mov    %rbx,%rax
   0x00000000004033d1 <+449>:	add    $0x1,%rax
   0x00000000004033d5 <+453>:	mov    %rax,0x205df4(%rip)        # 0x6091d0 <g.4372+16>
   0x00000000004033dc <+460>:	mov    %rsi,%rax
   0x00000000004033df <+463>:	mul    %rdx
   0x00000000004033e2 <+466>:	sub    %rdx,%rsi
   0x00000000004033e5 <+469>:	shr    %rsi
   0x00000000004033e8 <+472>:	add    %rdx,%rsi
   0x00000000004033eb <+475>:	shr    $0xd,%rsi
   0x00000000004033ef <+479>:	mov    %rsi,0x205dca(%rip)        # 0x6091c0 <g.4372>
   0x00000000004033f6 <+486>:	jmpq   0x4032fb <disk_geometry+235>
   0x00000000004033fb <+491>:	nopl   0x0(%rax,%rax,1)
   0x0000000000403400 <+496>:	callq  0x400e30 <__errno_location@plt>
   0x0000000000403405 <+501>:	mov    (%rax),%edi
   0x0000000000403407 <+503>:	callq  0x401050 <strerror@plt>
   0x000000000040340c <+508>:	mov    $0x406205,%edx
   0x0000000000403411 <+513>:	mov    %rax,%rcx
   0x0000000000403414 <+516>:	mov    $0x406211,%esi
   0x0000000000403419 <+521>:	mov    $0x1,%edi
   0x000000000040341e <+526>:	xor    %eax,%eax
   0x0000000000403420 <+528>:	callq  0x405230 <pr>
   0x0000000000403425 <+533>:	jmpq   0x4032a1 <disk_geometry+145>
   0x000000000040342a <+538>:	nopw   0x0(%rax,%rax,1)
   0x0000000000403430 <+544>:	callq  0x400e30 <__errno_location@plt>
   0x0000000000403435 <+549>:	mov    (%rax),%edi
   0x0000000000403437 <+551>:	callq  0x401050 <strerror@plt>
   0x000000000040343c <+556>:	mov    $0x406226,%edx
   0x0000000000403441 <+561>:	mov    %rax,%rcx
   0x0000000000403444 <+564>:	mov    $0x406211,%esi
   0x0000000000403449 <+569>:	mov    $0x1,%edi
   0x000000000040344e <+574>:	xor    %eax,%eax
   0x0000000000403450 <+576>:	callq  0x405230 <pr>
   0x0000000000403455 <+581>:	jmpq   0x4032be <disk_geometry+174>
   0x000000000040345a <+586>:	callq  0x400e80 <__stack_chk_fail@plt>
End of assembler dump.
```

**Comment by baruch** [comment]
This is a division by zero in the code:

```
	g.d_c = nsects / (hg.heads * hg.sectors);
```

The block device accessed doesn't have a geometry and we divide by zero.
